version: "2"

services:
  graalvm:
    image: graalvm
    volumes:
      - .:/graalvm
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 127.0.0.1:5005:5005
    stdin_open: true
    restart: always
