.PHONY: all
all: time-c-for time-c-for-shortCompil time-c-tcl-interpreter-for time-c-tcl-interpreter-for-dynamic time-c-tcl-native-for time-c-tcl-native-for-dynamic time-c-tcl-native-interpreter-for time-c-tcl-native-interpreter-for-dynamic time-cpp-tcl-interpreter-for time-cpp-tcl-interpreter-for-dynamic time-cpp-tcl-native-for time-java-c-for time-java-c-tcl-interpreter-for time-java-c-tcl-interpreter-for-dynamic time-java-c-tcl-interpreter-for-optimize time-java-c-tcl-interpreter-for-optimize-dynamic time-java-for time-tcl-for


time-c-for:
	cd c-for/ && make clean; make time

time-c-for-shortCompil:
	cd c-for-shortCompil/ && make clean; make time

time-c-tcl-interpreter-for:
	cd c-tcl-interpreter-for/ && make clean; make time

time-c-tcl-interpreter-for-dynamic:
#	cd c-tcl-interpreter-for-dynamic/ && make clean; make time

time-c-tcl-native-for:
	cd c-tcl-native-for/ && make clean; make time

time-c-tcl-native-for-dynamic:
#	cd c-tcl-native-for-dynamic/ && make clean; make time

time-c-tcl-native-interpreter-for:
	cd c-tcl-native-interpreter-for/ && make clean; make time

time-c-tcl-native-interpreter-for-dynamic:
#	cd c-tcl-native-interpreter-for-dynamic/ && make clean; make time

time-cpp-tcl-interpreter-for:
#	cd cpp-tcl-interpreter-for/ && make clean; make time

time-cpp-tcl-interpreter-for-dynamic:
#	cd cpp-tcl-interpreter-for-dynamic/ && make clean; make time

time-cpp-tcl-native-for:
#	cd cpp-tcl-native-for/ && make clean; make time

time-java-c-for:
	cd java-c-for/ && make clean; make time

time-java-c-tcl-interpreter-for:
	cd java-c-tcl-interpreter-for/ && make clean; make time

time-java-c-tcl-interpreter-for-dynamic:
#	cd java-c-tcl-interpreter-for-dynamic/ && make clean; make time

time-java-c-tcl-interpreter-for-optimize:
#	cd java-c-tcl-interpreter-for-optimize/ && make clean; make time

time-java-c-tcl-interpreter-for-optimize-dynamic:
#	cd java-c-tcl-interpreter-for-optimize-dynamic/ && make clean; make time

time-java-for:
	cd java-for/ && make clean; make time

time-tcl-for:
	cd tcl-for/ && make clean; make time
